site_name: geoindia

site_url: https://doke93.github.io/geoindia

repo_url: https://github.com/doke93/geoindia

theme:
    palette:
        scheme: preference
    name: material
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        - search.highlight
        # - navigation.expand
        # - navigation.tabs
    custom_dir: "docs/overrides"

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
          include_source: True
          ignore_h1_titles: True
          execute: True
          execute_ignore: ["*.ipynb"]
          
markdown_extensions:
    - attr_list
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

# extra:
#     analytics:
#         provider: google
#         property: UA-XXXXXXXXX-X

nav:
    - Home: index.md
    - Installation: installation.md
    - Usage: usage.md
    - Contributing: contributing.md
    - FAQ: faq.md
    - Changelog: changelog.md
    - Report Issues: https://github.com/doke93/geoindia/issues
    - API Reference:
          - geoindia module: geoindia.md
    - Examples:
        - examples/intro.ipynb
        - examples/folium.ipynb
        - examples/ipyleaflet.ipynb
        - examples/geoindia_demo.ipynb

